server:
  host: "0.0.0.0"
  port: "10000"

db:
  user: "kirill"
  password: "jcWHs2n0lco5H4Vqeoiue2KsIxlL0U8F"
  name: "postgresql://kirill:jcWHs2n0lco5H4Vqeoiue2KsIxlL0U8F@dpg-cstp0tbv2p9s73csfic0-a/go_market_db"
  host: "dpg-cstp0tbv2p9s73csfic0-a"
  port: "5432"