server:
  host: "0.0.0.0"
  port: "10000"

db:
  user: "kirill"
  password: "jcWHs2n0lco5H4Vqeoiue2KsIxlL0U8F"
  name: "go_market_db"
  host: "dpg-cstp0tbv2p9s73csfic0-a.frankfurt-postgres.render.com"
  port: "5432"
  sslmode: "enable"